version: '3.8'
services: 
    profileservice:
        build: .
        ports:
        - "8006:80"
        - "8007:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8007"
            ASPNETCORE_ENVIRONMENT: "Development"
            ConnectionStrings__ProfileConnection: ${DB_CONNECTION_STRING}
        volumes:
            - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/