// <auto-generated />
using System;
using DevelopmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevelopmentService.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20240124183745_updateFeedbackTable")]
    partial class updateFeedbackTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevelopmentService.Models.EmpFeedback", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("integer");

                    b.Property<string>("feedback")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("feedbackDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("overallScore")
                        .HasColumnType("integer");

                    b.HasKey("EmpId");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("DevelopmentService.Models.EmpPerformance", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("reviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("weaknesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmpId");

                    b.ToTable("performances");
                });
#pragma warning restore 612, 618
        }
    }
}
