version: '3.8'
services: 
    employmentservice:
        build: .
        ports:
        - "8005:80"
        - "8004:443"
        environment:
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8004"
            ASPNETCORE_ENVIRONMENT: "Development"
            ConnectionStrings__EmploymentConnection: ${DB_CONNECTION_STRING}
        volumes:
            - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/